global.mess = {
  owner: "FITUR INI BUAT RAJA KEGELAPAN, BUKAN BUAT PECUNDANG!!! 😡",
  group: "FITUR INI KHUSUS BUAT GRUP RUSUH!!! 😈",
  private: "FITUR INI CUMA BISA DIPAKE DI PRIVATE, BIAR GAK ADA YANG DENGER!!! 🤫",
  admin: "LU BUKAN ADMIN, MINGGIR!!! 😠",
  botadmin: "BOT HARUS JADI ADMIN DULU, BIAR BISA NGE-TROLL!!! 😈",
};
